### ISSUE TITLE
Performance difference of lower and upper in PO after applied advice data on device

### ISSUE THREAD

**Issue by QingleiCao** [ICLDisco/dplasma#124]
This issue is to track the issue, as detailed in the table of this PR (https://github.com/ICLDisco/dplasma/pull/118).

**Comment by abouteiller** [comment]
We have now merged #135 that set lower to be the default for all cases, and makes uplo a command line parameter. 

I don;'t think there is more we can do on our end about that issue. Please reopen if you have more ideas.
