### ISSUE TITLE
zpotrf max priority incorrect

### ISSUE THREAD

**Issue by omor1** [ICLDisco/dplasma#52]
## Describe the bug
`zpotrf_L` has the following comment:
```
/*
 * Priorities used in this jdf:
 *      - potrf_zpotrf(k)    : (MT-k)**3
 *      - potrf_zherk(k,m)   : (MT-m)**3 + 3 * (m - k)
 *      - potrf_ztrsm(m,k)   : (MT-m)**3 + 3 * (m - k) * (2 * MT - k - m - 1)
 *      - potrf_zgemm(m,n,k) : (MT-m)**3 + 3 * (m - n) * (2 * MT - m - n - 1) + 6 * (m - k)
 *
 * So max priority is:
 *      (MT - PRI_CHANGE)**3 + 3 * MT * (2 * MT - PRI_CHANGE - 1) + 6 * MT  < (MT**3 + 6 MT**2 + 3 MT)
 *
 * WARNING: If mt is greater than 1200, we might get integer overflow.
 */
```

Additionally, `PRI_MAX` is defined as:
```
PRI_MAX       [type = "int" hidden = on default = "(descA->mt * ( 3 + descA->mt * ( 2 + descA->mt )))" ]
```

There are a couple of issues here.
* First, the priority for `potrf_zgemm` as defined later in the file is actually `(MT-m)**3 + 3 * (m - n) * (2 * MT - m - n - 3) + 6 * (m - k)` (that's 2 * MT - m - n - **3**), so the comment is incorrect.
* Secondly, the simplified max priority in the comment should be `MT**3 + 6 MT**2 + 6 MT` (that's **6** MT).
* Lastly, the actual `PRI_MAX` as defined is `MT**3 + 2 MT**2 + 3 MT`, which is incorrect for both the original and corrected simplified max priority in the comment.

The same is true for `zpotrf_U`, though the priority definitions used are slightly different in recognition of the matrix shape.

In practice, there is probably little reason to believe that this has a significant impact on performance. However, I'd appreciate confirmation that my observation is correct and fixed. I originally noted the issue in HiCMA's dpotrf, which inherited the priorities used here.

**Comment by bosilca** [comment]
I pushed a patch to fix the comment. The idea behind PRI_CHANGE was to provide a very basic form of lookahead, respect priorities up to few panels ahead, and then let everything at the max priority. The priority working on a reverse scale, the far away tasks will be used as fill-ins when nothing else is available for execution.

**Comment by omor1** [comment]
> I pushed a patch to fix the comment. The idea behind PRI_CHANGE was to provide a very basic form of lookahead, respect priorities up to few panels ahead, and then let everything at the max priority. The priority working on a reverse scale, the far away tasks will be used as fill-ins when nothing else is available for execution.

That was my understanding :). That fixes the incorrect comment, but doesn't align the defined `PRI_MAX` with the corrected, simplified version—though as @QingleiCao noted, you'd probably need some contrived example where `PRI_MAX` is less than the "normal" task priority and causes priority inversion.
